name: MinigameParadise
main: com.enderzombi102.MinigameParadise.MinigameParadise
version: 1.0.0
api-version: 1.13
commands:
   mode:
      description: Starts/stops a gamemode
      usage: /mode <start|stop> <mode> [parameters]
      permission: MinigameParadise.modifyGamemodeState
   listplayers:
      description: list all players
      usage: /listplayers <gamemode> [onlynumber]
      permission: MinigameParadise.listPlayers