name: MinigameParadise
main: com.enderzombi102.MinigameParadise.MinigameParadise
version: 1.0.0
api-version: 1.13
commands:
   modestart:
      description: Start a gamemode
      usage: /modestart <mode> [parameters]
      permission: MinigameParadise.startGamemode
   modestop:
      description: Stops a gamemode
      usage: /modestop <mode>
      permission: MinigameParadise.stopGamemode
   listplayers:
      description: list all players
      usage: /listplayers <gamemode> [onlynumber]
      permission: MinigameParadise.listPlayers