name: MinigameParadise
main: com.enderzombi102.MinigameParadise.MinigameParadise
version: 1.0.0
api-version: 1.13
commands:
   start:
      description: Start a gamemode
      usage: /start <mode> [parameters]
      permission: MinigameParadise.startGamemode
   stop:
      description: Stops a gamemode
      usage: /stop <mode>
      permission: MinigameParadise.stopGamemode
   listplayers:
      description: list all players
      usage: /listplayers <gamemode> [onlynumber]
      permission: MinigameParadise.listPlayers